### PR TITLE
Capitalize methods

### PR DESCRIPTION
**Pull request by bartekn**

### CODE REVIEW

**Comment by nullstyle** [comment]
+1

This will work for now, but at some point we should refactor this to use `camelize`: http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-camelize

In this case, it would just be `m.name.camelize`

**Comment by bartekn** [comment]
I tried to use `camelize` but it also makes every letter except the first lower case, so `accountID` becomes `Accountid'.

**Comment by nullstyle** [comment]
There are system's to work around that, by adding custom inflections, but point taken.   I can look at it more in the future.

**Comment by bartekn** [comment]
Merging current solution.

**Pull request merged**
